name: flutter_application_1
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <4.0.0" # Ensure that the SDK constraint is compatible with null safety

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.3 # Update to a version that supports null safety
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2

flutter:
  uses-material-design: true
